// flow-typed signature: 8539efdd2cc3aab4bc1fd4c75124ff0c
// flow-typed version: <<STUB>>/path-normalize_vv1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path-normalize/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path-normalize/index' {
  declare module.exports: $Exports<'path-normalize'>;
}
declare module 'path-normalize/index.js' {
  declare module.exports: $Exports<'path-normalize'>;
}
declare module 'path-normalize/test.js' {
  declare module.exports: $Exports<'path-normalize/test'>;
}
